min_edge_weight: 1
n_top: 3
timeslice_interval: 10
raw_data_path: "outputs/asf.pickle"
network_path: "outputs/G_library.pickle"
G_timeslices_path: "outputs/G_timeslices.pickle"

earliest_timeslice_graph_name: "G_timeslice_0.html"
latest_timeslice_graph_name: "G_timeslice_6.html"

gb_timeslice_x: "G_timeslice_3"
gb_timeslice_y: "G_timeslice_4"
gb_cluster_name: "britain-great-energy"
gb_graph_name: "britain_great_energy.html"

congress_timeslice_x: "G_timeslice_2"
congress_timeslice_y: "G_timeslice_3"
congress_cluster_name: "congress-energy-power"
congress_graph_name: "congress_energy_power.html"
